### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wongmia** [Graph-COM/ED-HNN#1]
Hi,

Thanks for sharing the codes. This paper is very interesting. 

When I try to reproduce the results and run 'python train.py --method HCHA --dname senate-committees-100 --All_num_layers 8 --MLP_num_layers 2 --MLP2_num_layers 2 --MLP3_num_layers 2 --Classifier_num_layers 2 --MLP_hidden 512 --Classifier_hidden 256 --aggregate mean --restart_alpha 0.5 --lr 0.001 --wd 0 --epochs 500 --runs 1 --feature_noise 1.0 --cuda 0 --data_dir data/ --raw_data_dir raw_data/senate-committees', I get an error.

Error: 'ValueError: Encountered tensor with size 597 in dimension 0, but expected size 282.'. in **line 161, models/hcha.py**. Could you give me some suggestions on how to solve this problem if you are available? Thanks in advance.

Cheers

**Comment by peihaowang** [comment]
Hi,

Thanks for your interest. I have tested the command you used above. It looks all good. You may regenerate the data by removing the `data/` directory. If still not working, please feel free to reopen the issue maybe with more details please.

Thanks
