### ISSUE TITLE
Could you please provide the code or dataset for generating the synthetic dataset?

### ISSUE THREAD

**Issue by yuwxyun275** [Graph-COM/ED-HNN#4]
Your work is very innovative and has promoted the development of the community. However, I don’t quite understand how to generate the synthetic dataset in the paper. Can you provide the code or dataset or the idea of ​​generating it?

**Comment by Mingbao278** [comment]
Thank you very much for your great work! I encountered the same issue as mentioned. Could you kindly share the synthetic dataset, so that I can continue with the subsequent experiments?
